#!/bin/bash

# Prompts user for new file name
printf "New File Name:\t"

# Sets fileName as variable for input
read fileName

# Write the base file template
echo "// Task # - Tests FILE

const assert = require('assert');
const FUNCITON = require('FILE');

describe('FUNCITON', function() {
  it('DESCRIPTION OF TEST', function() {
    assert.strictEqual(FUNCTION(A, B), EXPECTED);
  });
});" > "$fileName"

# Makes new file executable
chmod u+x "$fileName"

# Opens new file with vi
vi "$fileName"
